### ISSUE TITLE
failing test: f2361_sort_nested_files

### ISSUE THREAD

**Issue by oconnor663** [BurntSushi/ripgrep#2794]
### Please tick this box to confirm you have reviewed the above.

- [X] I have a different issue.

### What version of ripgrep are you using?

master (bb8601b2bafb5e68181cbbb84e6ffa4f7a72bf16)

### How did you install ripgrep?

Not installed, just running `cargo test` in the repo.

### What operating system are you using ripgrep on?

CentOS Stream 9, with an XFS root filesystem

### Describe your bug.

This doesn't repro every time, maybe 1/5 or 1/10.

```
$ git clone https://github.com/BurntSushi/ripgrep
...
$ cd ripgrep
$ cargo test f2361_sort_nested_files
...
test feature::f2361_sort_nested_files ... FAILED

failures:

---- feature::f2361_sort_nested_files stdout ----
thread 'feature::f2361_sort_nested_files' panicked at tests/feature.rs:952:5:

printed outputs differ!

expected:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
foo
dir/bar

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

got:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dir/bar
foo

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    feature::f2361_sort_nested_files
```

### What are the steps to reproduce the behavior?

see above

### What is the actual behavior?

test failure above

### What is the expected behavior?

tests should pass

**Comment by sukhmel** [comment]
Same here when building on MacOS with Nix, ripgrep version 14.1.0

> error: test failed, to rerun pass `--test integration`
> error: builder for '/nix/store/k6djbylmb9fdz4ss0dxszyx8qr9bhmcd-ripgrep-14.1.0.drv' failed with exit code 101
> thread 'feature::f2361_sort_nested_files' panicked at tests/feature.rs:960:5

output is otherwise same. The second attempt was successful, so maybe a flaky test?
